import { MigrationInterface, QueryRunner } from 'typeorm';

export class UserClassCompositePK1752000000000 implements MigrationInterface {
  name = 'UserClassCompositePK1752000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Drop the old primary key constraint
    await queryRunner.query(
      `ALTER TABLE "user_class" DROP CONSTRAINT "PK_241fcc163fef37b7105a3038615"`,
    );
    // Remove the autogenerated id column
    await queryRunner.query(`ALTER TABLE "user_class" DROP COLUMN "id"`);
    // Add composite primary key on (userId, classId)
    await queryRunner.query(
      `ALTER TABLE "user_class" ADD CONSTRAINT "PK_user_class_userId_classId" PRIMARY KEY ("userId","classId")`,
    );
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "IDX_user_class_userId_classId" ON "user_class" ("userId","classId")`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_user_class_userId_classId"`,
    );
    // Remove composite primary key
    await queryRunner.query(
      `ALTER TABLE "user_class" DROP CONSTRAINT "PK_user_class_userId_classId"`,
    );
    // Recreate id column as serial and restore original primary key
    await queryRunner.query(
      `ALTER TABLE "user_class" ADD COLUMN "id" SERIAL NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "user_class" ADD CONSTRAINT "PK_241fcc163fef37b7105a3038615" PRIMARY KEY ("id")`,
    );
  }
}
