apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eevee-ingress
  namespace: default
  annotations:
    # Annotations para o NGINX Ingress Controller
    cert-manager.io/cluster-issuer: "letsencrypt-production" 
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx # Especifica o IngressClass se necessário
  tls:
    - hosts:
        - frontend.eeeveecodelab.online
        - api.eeveecodelab.online
      secretName: eevee-tls-secret # O nome do Secret que contém os certificados TLS
  rules:
    # 1. Regra para a API NestJS
    - host: "api.eeveecodelab.online"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scheduler-api-service # O nome do Service da sua API!
                port:
                  number: 3000 

    # 2. Regra para o Frontend Next.js
    - host: "frontend.eeveecodelab.online"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eevee-front-service # O nome do Service do seu Next.js!
                port:
                  number: 80 