import * as assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import { DataSource } from 'typeorm';
import { ConfigService } from '@nestjs/config';
import { AppDataSource } from '../data-source';
import { PlatformInvitations1790265600000 } from '../src/migrations/1790265600000-PlatformInvitations';
import { InvitationService } from '../src/invitation/invitation.service';
import { PlatformInvitation } from '../src/invitation/invitation.entity';
import { User } from '../src/user/entities/user.entity';
import { UserClass } from '../src/user-class/entities/user-class.entity';
import { Class } from '../src/class/entities/class.entity';
import { HashUtils } from '../src/utils/hash.utils';

async function main() {
  await AppDataSource.initialize();
  const runner=AppDataSource.createQueryRunner();
  await runner.startTransaction();
  try {
    if(!await runner.hasTable('platform_invitation')) await new PlatformInvitations1790265600000().up(runner);
    const manager=runner.manager;
    const db={manager,getRepository:(entity:any)=>manager.getRepository(entity),transaction:(fn:any)=>manager.transaction(fn)} as unknown as DataSource;
    const mails:{to:string;text:string;html:string}[]=[];
    let sendSuccess=true;
    let admin=true;
    const service=new InvitationService(db,{sendEmail:async(params:any)=>{mails.push(params);return {success:sendSuccess};}} as any,new ConfigService({FRONT_URL:'https://eevee.example.test'}),{getUser:()=>({userId:1,isAdmin:admin})} as any);
    const suffix=randomBytes(8).toString('hex');
    const groups=await manager.save(Class,[manager.create(Class,{name:`Invitation test ${suffix} A`}),manager.create(Class,{name:`Invitation test ${suffix} B`})]);
    const classIds=groups.map(c=>c.id);
    const email=`invite-${suffix}@example.test`;
    const token=()=>new URL(mails[mails.length-1].text.match(/https:\/\/\S+/)![0]).hash.slice('#token='.length);
    admin=false;
    await assert.rejects(service.create({email,name:'Ana',classIds}),/Forbidden/);
    await assert.rejects(service.list(),/Forbidden/);
    admin=true;
    await assert.rejects(service.create({email,name:'Ana',classIds:[2147483647]}),/turmas/);
    const first=await service.create({email,name:'Ana <script>',classIds});
    const firstToken=token();
    assert.equal(first.deliveryStatus,'sent');
    assert(mails[0].html.includes('&lt;script&gt;'));
    assert.equal(await manager.count(User,{where:{email}}),0,'Invitation must not create a user before acceptance');
    const secretRow=await manager.getRepository(PlatformInvitation).createQueryBuilder('i').addSelect('i.tokenHash').where('i.id=:id',{id:first.id}).getOneOrFail();
    assert.equal(secretRow.tokenHash.length,64);
    assert.notEqual(secretRow.tokenHash,firstToken);
    assert(!JSON.stringify(await service.list()).includes(firstToken));
    assert(!('tokenHash' in (await service.list()).data.find(i=>i.id===first.id)!));
    await assert.rejects(service.create({email,name:'Ana',classIds}),/convite ativo/);
    assert.equal((await service.inspect(firstToken)).existingAccount,false);
    await assert.rejects(service.accept({token:firstToken,password:'short'}),/8 caracteres/);
    await service.accept({token:firstToken,password:'Personal-password-123'});
    const user=await manager.findOneByOrFail(User,{email});
    assert.equal(user.isAdmin,false);
    assert(HashUtils.comparePassword('Personal-password-123',user.passwordHash));
    assert.equal(await manager.count(UserClass,{where:{userId:user.id}}),2);
    await assert.rejects(service.accept({token:firstToken,password:'Personal-password-123'}),/Convite inválido/);
    await assert.rejects(service.resend(first.id),/aceito/);
    const existing=await service.create({email,name:'Changed name',classIds});
    const existingToken=token();
    assert.equal((await service.inspect(existingToken)).existingAccount,true);
    await assert.rejects(service.accept({token:existingToken,password:'wrong-password'}),/senha atual/);
    await service.accept({token:existingToken,password:'Personal-password-123'});
    const unchanged=await manager.findOneByOrFail(User,{email});
    assert.equal(unchanged.passwordHash,user.passwordHash);
    assert.equal(unchanged.name,user.name);
    assert.equal(await manager.count(UserClass,{where:{userId:user.id}}),2);
    const revocable=await service.create({email:`revoke-${email}`,name:'Bruno',classIds});
    const oldToken=token();
    await assert.rejects(service.resend(revocable.id),/um minuto/);
    await manager.update(PlatformInvitation,revocable.id,{sentAt:new Date(Date.now()-120000)});
    await service.resend(revocable.id);
    const newToken=token();
    assert.notEqual(newToken,oldToken);
    await assert.rejects(service.inspect(oldToken),/Convite inválido/);
    await service.revoke(revocable.id);
    await assert.rejects(service.accept({token:newToken,password:'Personal-password-123'}),/Convite inválido/);
    sendSuccess=false;
    const failed=await service.create({email:`failed-${email}`,name:'Carla',classIds});
    assert.equal(failed.deliveryStatus,'failed');
    await assert.rejects(service.inspect(token()),/Convite inválido/);
    sendSuccess=true;
    const expired=await service.create({email:`expired-${email}`,name:'Diego',classIds});
    const expiredToken=token();
    await manager.update(PlatformInvitation,expired.id,{expiresAt:new Date(Date.now()-1000)});
    await assert.rejects(service.accept({token:expiredToken,password:'Personal-password-123'}),/Convite inválido/);
    const page=await service.list(1,2);
    assert.equal(page.data.length,2);
    assert(page.meta.total>=5);
    console.log('Invitation integration passed: admin checks, class validation, hashed tokens, no precreated accounts, email escaping, acceptance/enrollment, replay, existing-password preservation, resend rotation, revoke, expiry, failed delivery, pagination. Mail was mocked.');
  } finally {
    await runner.rollbackTransaction();
    await runner.release();
    await AppDataSource.destroy();
    console.log('All test database changes rolled back. No emails sent.');
  }
}
main().catch(error=>{console.error(error.message);process.exitCode=1;});
