apiVersion: apps/v1
kind: Deployment
metadata:
  name: eevee-front-deployment
  namespace: default
  labels:
    app: eevee-front
    tier: frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eevee-front 
  template:
    metadata:
      labels:
        app: eevee-front
    spec:
      containers:
      - name: eevee-front
        # Aqui você colocaria a imagem Docker gerada pelo seu GitHub Actions
        image: docker.io/library/eevee-front:latest 
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 3000 # A porta onde o seu NestJS roda (exemplo)
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "384Mi" # Limite seguro para não estourar a RAM