export enum Route {
  Assignment = "assignment",
  Login = "login",
  ForgotPassword = "forgot-password",
  ResetPassword = "reset-password",
  Workspace = "workspace",
  Admin = "admin",
  AdminAssignments = "/admin/assignments",
  AdminUsers = "admin/users",
  AdminClasses = "admin/classes",
  AdminAssignmentCreate = "admin/assignments/create",
  AdminTemplate = "/admin/templates",
  AdminAttempts = "/admin/attempts",
  AssignmenstUsersSuspensions = "suspensions",
  Classes = "classes",
  ClassesAssignments = "classes/assignments",
}
