export const ASSIGNMENT_FORM_TEXT = {
  VALIDATION: {
    TITLE_REQUIRED: "Título é obrigatório",
    DESCRIPTION_REQUIRED: "Descrição é obrigatória",
    MAX_ATTEMPTS_REQUIRED: "Máximo de tentativas é obrigatório",
    MAX_ATTEMPTS_MIN: "Deve ser pelo menos 1",
    WORKER_TYPE_REQUIRED: "Tipo de worker é obrigatório",
    BOILERPLATE_REQUIRED: "Boilerplate é obrigatório",
    CLASS_REQUIRED: "Turma é obrigatória",
    DUEDATECANNOTLATERTHANSTARTDATE: "A data de entrega não pode ser anterior à data de início",
  },
  STEPS: {
    CONFIG: "Configuração",
    TEMPLATES: "Templates",
    BOILERPLATE: "Boilerplate",
    INIT_SQL: "Script SQL Inicial",
    REVIEW: "Revisão",
  },
  CONFIG: {
    TITLE: "Informacoes da Atividade",
    ACTIVITY_TITLE_LABEL: "Titulo",
    ACTIVITY_TITLE_PLACEHOLDER: "Titulo da Atividade",
    DESCRIPTION_LABEL: "Descricao",
    DESCRIPTION_PLACEHOLDER: "Descreva o que os alunos devem fazer",
    EXPAND_DESCRIPTION: "Expandir",
    MINIMIZE_DESCRIPTION: "Minimizar",
    CLASS_LABEL: "Disciplina do Trabalho",
    CLASS_PLACEHOLDER: "Selecione uma turma",
    WORKER_TYPE_LABEL: "Tipo de Worker",
    WORKER_TYPE_TOOLTIP: "Kit de ferramentas para corrigir os exercicios.",
    WORKER_TYPE_DESCRIPTION: "Selecione o tipo de worker que sera utilizado para corrigir os exercicios dos alunos.",
    MAX_ATTEMPTS_LABEL: "Maximo de Tentativas",
    MAX_ATTEMPTS_TOOLTIP: "Quantidade de tentativas para realizar a tarefa.",
    MAX_ATTEMPTS_PLACEHOLDER: "Numero maximo de tentativas permitidas",
    ANSWER_KEY_VISIBLE_LABEL: "Visibilidade do gabarito",
    ANSWER_KEY_VISIBLE_TOOLTIP: "Deixe ativado quando desejar que os alunos visualizem o gabarito.",
    ALLOW_COPY_PASTE_LABEL: "Permitir copiar e colar",
    ALLOW_COPY_PASTE_TOOLTIP: "Permite copiar e colar conteúdos somente dentro do ambiente da atividade. Conteúdos externos continuarão bloqueados.",
    PROJECT_IMPORT_CONTROL_LABEL: "Controle de importação de projetos",
    PROJECT_IMPORT_CONTROL_TOOLTIP: "Permite que o aluno importe o último projeto enviado para correção em outra atividade compatível desta turma.",
  },
  BOILERPLATE: {
    TITLE: "Código Boilerplate",
    TOOLTIP: "Código que será fornecido ao aluno no início do trabalho para ser usado como base para o desenvolvimento dos exercícios.",
    DESCRIPTION: (workerName: string) =>`Forneça o código que será entregue ao aluno no início do trabalho. Certifique-se de que o código esteja alinhado com o tipo de worker selecionado. Segue um exemplo de código boilerplate para o tipo de worker "${workerName}":`,
  },
  INIT_SQL: {
    TITLE: "Script SQL de Inicialização",
    DESCRIPTION:
      "Forneça o script SQL que será executado para inicializar o banco de dados PostgreSQL antes da execução do código do aluno. Utilize este campo para criar tabelas, inserir dados iniciais (seeds), etc.",
  },
  REVIEW: {
    TITLE: "Revisão Final",
    DESCRIPTION: "Revise todas as informações antes de criar o assignment",
    CONFIG_TITLE: "Configurações",
    ACTIVITY_TITLE: "Título",
    CLASS: "Turma",
    DESCRIPTION_LABEL: "Descrição",
    WORKER_TYPE: "Tipo de Worker",
    MAX_ATTEMPTS: "Máximo de Tentativas",
    TEMPLATES_ADDED: (count: number) => `Templates de teste adicionados (${count})`,
    NO_TEMPLATE_SELECTED: "Nenhum template selecionado.",
  },
  ERRORS: {
    ASSIGNMENT_LOAD_TITLE: "Não foi possível carregar o assignment",
    ASSIGNMENT_LOAD_DESCRIPTION: "Não conseguimos carregar os dados deste assignment para edição.",
    CLASSES_LOAD_TITLE: "Não foi possível carregar as turmas",
    CLASSES_LOAD_DESCRIPTION: "As turmas necessárias para criar ou editar o assignment não puderam ser carregadas.",
    RETRY: "Tentar novamente",
    WEIGHT_SUM: (sum: number) => `A soma dos pesos deve ser exatamente 100% (atual: ${sum.toFixed(2)}%).`,
  },
  NAVIGATION: {
    LOADING: "Carregando...",
    PREVIOUS: "Anterior",
    CONTINUE: "Continuar",
    UPDATE: "Atualizar Atividade",
    CREATE: "Criar Atividade",
  },
} as const;
