name: Deploy Front

on:
    push:
        branches:
        - main
        paths:
        - 'front/**'
        - 'images/node/**'
        - 'images/javascript-default/**'
        - '.github/actions/remote-kubectl/**'
        - '.github/workflows/deploy-front.yaml'

env:
    REGISTRY: ghcr.io
    FRONT_IMAGE: ${{ vars.FRONT_IMAGE }}


jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v4
            
            - name: Login no GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GHCR_TOKEN }}
            
            - name: Build e Push da Imagem Docker
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./front/Dockerfile
                push: true
                build-args: |
                    NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
                    APP_ENV=${{ vars.APP_ENV }}
                tags: |
                    ${{ env.REGISTRY }}/${{ env.FRONT_IMAGE }}:latest
                    ${{ env.REGISTRY }}/${{ env.FRONT_IMAGE }}:${{ github.sha }}

            - name: Atualiza imagem e reinicia o pod
              uses: ./.github/actions/remote-kubectl
              with:
                host: ${{ vars.DEPLOY_HOST }}
                username: ${{ vars.DEPLOY_USER }}
                port: "${{ vars.DEPLOY_SSH_PORT || '22' }}"
                private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
                known-hosts: ${{ secrets.DEPLOY_SSH_KNOWN_HOSTS }}
                script: |
                  kubectl set image deployment/eevee-front-deployment eevee-front=${{ env.REGISTRY }}/${{ env.FRONT_IMAGE }}:${{ github.sha }} -n default
