name: Deploy Platform API

on:
    push:
        branches:
        - main
        paths:
        - 'platform-api/**'
        - '.github/workflows/deploy-platform-api.yaml'

env:
    REGISTRY: ghcr.io
    PLATFORM_API_IMAGE: ${{ vars.PLATFORM_API_IMAGE }}

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout do código
              uses: actions/checkout@v3
            
            - name: Login no GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GHCR_TOKEN }}
            
            - name: Build e Push da Imagem Docker
              uses: docker/build-push-action@v3
              with:
                context: ./platform-api
                push: true
                tags: |
                    ${{ env.REGISTRY }}/${{ env.PLATFORM_API_IMAGE }}:latest
                    ${{ env.REGISTRY }}/${{ env.PLATFORM_API_IMAGE }}:${{ github.sha }}

            - name: Configurar kubectl
              uses: azure/setup-kubectl@v3

            - name: Atualiza Configuração do Kubernetes
              env:
                KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
              run: |
                mkdir -p $HOME/.kube
                echo "${KUBE_CONFIG_DATA}" | base64 --decode > $HOME/.kube/config
                chmod 600 $HOME/.kube/config

            - name: Atualiza Platform API e seus workers
              run: |
                kubectl set image deployment/platform-api-deployment platform-api=${{ env.REGISTRY }}/${{ env.PLATFORM_API_IMAGE }}:${{ github.sha }} -n default
